### ISSUE TITLE
Ability to sign up

### ISSUE THREAD

**Issue by rubur-webbeds** [rubur-webbeds/jellytoring-web#1]
### Description  
AS A new user
I WANT TO be able to sign up
IN ORDER TO access the page content and services

### Acceptance Criteria  
The user has to provide: 
* Name
* Email
* Institution
* Country
* Interest

The user has to verify it's email

### Tasks  
- [ ] DB: Add Interests and countries
- [ ] UI: Add SIGN UP button in the header
- [ ] UI: Display a form to register
- [ ] API: Create User controller
- [ ] API: Send email verification

**Comment by rubur-webbeds** [comment]
#### Users controller
`GET /users` - gets all the users
`GET /users/4` - gets the user information with id 4
`POST /users` - creates a new user. Used for signin up
`PUT /users/4`

#### Sessions controller
`POST /session` - creates a new session for the user in the body (email and pwd). Used for loggin in.
`DELETE /session` - Log out
