### ISSUE TITLE
Ability to display uploaded images

### ISSUE THREAD

**Issue by rubur-webbeds** [rubur-webbeds/jellytoring-web#11]
### Description  
AS A logged in user
I WANT TO be able to see all the images uploaded by me

### Notes
After login, the user is redirected to /dashboard where the images will be listed in.

### Tasks  
- [ ] VM: configure nginx to serve images
- [ ] API: create endpoint
- [ ] UI: add api request
