### ISSUE TITLE
Improve UX

### ISSUE THREAD

**Issue by rubur-webbeds** [rubur-webbeds/jellytoring-web#17]
### Description 
AS A user
I WANT TO navigate comfortably in the web 

### Tasks  
- [ ] UI: check if the user is logged always
- [ ] UI: change page title
- [ ] UI: at login, send form pressing Enter key
- [ ] UI: make Jellytoring header a button to /dashboard
- [ ] UI: add logout
