### ISSUE TITLE
Ability to recover user's password

### ISSUE THREAD

**Issue by rubur-webbeds** [rubur-webbeds/jellytoring-web#36]
### Description  
AS A registered user
I WANTO TO be able to create a new password when I forgot the old one  

### Acceptance Criteria
The user first types his email, the app checks the user is already registered, then an email is sent with a special (secret) url that redirects him to the actual password recovery form. (A new email is sent to notify the password change???). Finally the user logs in with the new password.

### Tasks  
- [x] UI: Add 'Forgot my password' link in Login
- [x] UI: Create PasswordRecoveryEmail view
- [x] UI: Create PasswordRecoveryForm view
- [x] DB: Create PasswordRecovery table (similar to EmailConfirmation)
- [x] API: Create PasswordRecovery controller (to create GUID)
- [x] API: On Users controller create PUT action

**Comment by rubur-webbeds** [comment]
Done
