### ISSUE TITLE
Ability to sign in

### ISSUE THREAD

**Issue by rubur-webbeds** [rubur-webbeds/jellytoring-web#4]
### Description  
AS A registered user
I WANT TO sign in
IN ORDER TO access the page content and services with my account

### Related issues
Closely related to https://github.com/rubur-webbeds/jellytoring-web/issues/1 - Ability to sign up

### Tasks  
- [ ] UI: create login form
- [ ] UI: display logged in user
- [ ] API: create session controller
- [ ] API: generate JWT
