### ISSUE TITLE
Ability to label an image

### ISSUE THREAD

**Issue by rubur-webbeds** [rubur-webbeds/jellytoring-web#5]
### Description  
AS A user
I WANT TO upload an image and label/tag it's content
IN ORDER TO train the ML model  

### Tasks  
- [ ] DB: store jellyfish spices
- [ ] DB: create annotation table related to an image
- [ ] API: create endpoint to store annotation and image
- [ ] UI: create labelling tool

### Notes
create a new US for free text labelling (email notification to admins)  

#### JSON schema
```
{
  "annotation": {
    "filename": "GOPR5439 06.jpg",
    "size": {
      "width": "1280",
      "height": "720",
      "depth": "3"
    },
    "objects": [
    {
      "name": "pelagia",
      "bndbox": {
        "xmin": "30",
        "ymin": "447",
        "xmax": "65",
        "ymax": "479"
      },
     {...}
     ]
  }
}
```

#### DB schema
create table image_annotations (id, image_id, width, height, depth)
create table image_annotations_objects (annotation_id, species_id, xmin, ymin, xmax, ymax)

**Comment by rubur-webbeds** [comment]
Won't do. Out of scope.
