### ISSUE TITLE
Ability to update user roles

### ISSUE THREAD

**Issue by rubur-webbeds** [rubur-webbeds/jellytoring-web#6]
### Description  
AS A admin user
I WANT TO get a list of all the registered users and update the role to some of them.   

### Acceptance Criteria
- Only admins can do this
- Feature housed in the admin module
- Email notification

### Tasks  
- [ ] UI: display current users
- [ ] API: allow updating the role of a user
- [ ] API: send email
